public class findTheDifference {

    /*
    You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.



Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"


Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
     */

    public char findTheDifference(String s, String t) {

        if (s.length() == 0) {
            return t.charAt(0);
        }

        int totals = 0;
        int totalt = 0;

        for (int i = 0; i < s.length(); i++) {

            int  svalue = s.charAt(i);
            totals = totals + svalue;

            int  tvalue = t.charAt(i);
            totalt = totalt + tvalue;

        }

        int tvalue = t.charAt(t.length()-1);
        totalt = totalt + tvalue;

        int diff = totalt - totals;

        char res = (char) diff;

        return res;



    }

}
